# Full struct in cmd/prowgen/prowgen.go#Config

config:
  branches:
    "source_image_cli":
      openShiftVersions:
        - 4.13
        #- 4.11

repositories:
  - org: mgencur
    repo: serverless-operator
    promotion:
      namespace: knative
    imagePrefix: serverless
    imageNameOverrides:
      serverless-operator: bundle
    slackChannel: "#serverless-ci"
    dockerfiles:
      matches:
        - "knative-operator/.*"
        - "openshift-knative-operator/.*"
        - "serving/metadata-webhook/.*"
        - "serving/ingress/.*"
        - "olm-catalog/serverless-operator/Dockerfile"
        - "olm-catalog/serverless-operator/index/Dockerfile"
    e2e:
      matches:
        - "^operator-e2e$"
        - "^upstream-e2e$"
        - "^upstream-e2e-kafka$"
        - "^test-upgrade$"
        - "^mesh-e2e$"
        - "^mesh-upgrade$"
        - "^ui-e2e$"
        - "^kitchensink-e2e$"
        - "^kitchensink-upgrade$"
    resources:
      '*':
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
