# Full struct in cmd/prowgen/prowgen.go#Config

config:
  branches:
    main:
      openShiftVersions:
        - version: "4.14"
          cron: "0 4 * * *"
          # Note: customConfigs section below hardcodes OCP versions in a few places. They must be updated.
          generateCustomConfigs: true
        - version: "4.11"
          cron: "0 6 * * *"
          onDemand: true

repositories:
  - org: openshift-knative
    repo: serverless-operator
    promotion:
      namespace: knative
    imagePrefix: serverless
    imageNameOverrides:
      serverless-operator: bundle
    slackChannel: "#serverless-ci"
    ignoreConfigs:
      matches:
        - ".*main.yaml$"
        - ".*lp-interop.*"
        - ".*lp-interop.*"
    dockerfiles:
      matches:
        - "knative-operator/.*"
        - "openshift-knative-operator/.*"
        - "serving/metadata-webhook/.*"
        - "serving/ingress/.*"
        - "olm-catalog/serverless-operator/Dockerfile"
        - "olm-catalog/serverless-operator/index/Dockerfile"
    e2e:
      - match: "^operator-e2e$"
      - match: "^test-upgrade$"
      - match: "^upstream-e2e$"
        ignoreError: true
        skipCron: true
      - match: "^upstream-e2e-kafka$"
        ignoreError: true
      - match: "^mesh-e2e$"
        onDemand: true
        ignoreError: true
        timeout: 4h0m0s
      - match: "^mesh-upgrade$"
        onDemand: true
        ignoreError: true
        skipCron: true
      - match: "^ui-e2e$"
        onDemand: true
        runIfChanged: "test/ui"
        ignoreError: true
      - match: "^kitchensink-e2e$"
        onDemand: true
        ignoreError: true
      - match: "^kitchensink-upgrade$"
        onDemand: true
        ignoreError: true
    resources:
      '*':
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
    customConfigs:
      - name: "aws-ovn" # Results in openshift-knative-serverless-operator-<BRANCH>__<OCP_VERSION>-aws-ovn.yaml
        releaseBuildConfiguration:
          tests:
            - as: e2e-aws-ovn-continuous
              cron: 0 0 * * 0
              steps:
                cluster_profile: aws
                test:
                  - as: operator-e2e
                    commands: make test-e2e-with-kafka
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                  - as: knative-serving-eventing-e2e
                    commands: make test-upstream-e2e-no-upgrade
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                  - as: knative-eventing-kafka-broker-e2e
                    commands: make test-upstream-e2e-kafka-no-upgrade
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                workflow: openshift-e2e-aws-ovn
              timeout: 8h0m0s
      - name: "azure" # Results in openshift-knative-serverless-operator-<BRANCH>__<OCP_VERSION>-azure.yaml
        releaseBuildConfiguration:
          tests:
            - as: e2e-azure-continuous
              cron: 0 0 * * 0
              steps:
                cluster_profile: azure4
                test:
                  - as: operator-e2e
                    commands: make test-e2e-with-kafka
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                  - as: knative-serving-eventing-e2e
                    commands: make test-upstream-e2e-no-upgrade
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                  - as: knative-eventing-kafka-broker-e2e
                    commands: make test-upstream-e2e-kafka-no-upgrade
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                workflow: openshift-e2e-azure
              timeout: 8h0m0s
      - name: "gcp" # Results in openshift-knative-serverless-operator-<BRANCH>__<OCP_VERSION>-gcp.yaml
        releaseBuildConfiguration:
          tests:
            - as: e2e-gcp-continuous
              cron: 0 0 * * 0
              steps:
                cluster_profile: gcp
                test:
                  - as: operator-e2e
                    commands: make test-e2e-with-kafka
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                  - as: knative-serving-eventing-e2e
                    commands: make test-upstream-e2e-no-upgrade
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                  - as: knative-eventing-kafka-broker-e2e
                    commands: make test-upstream-e2e-kafka-no-upgrade
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                workflow: openshift-e2e-gcp
              timeout: 8h0m0s
      - name: "hypershift" # Results in openshift-knative-serverless-operator-<BRANCH>__<OCP_VERSION>-hypershift.yaml
        releaseBuildConfiguration:
          base_images:
            hypershift-operator:
              name: "4.14"
              namespace: ocp
              tag: hypershift-operator
            upi-installer:
              name: "4.14"
              namespace: ocp
              tag: upi-installer
          releases:
            latest:
              integration:
                include_built_images: true
                name: "4.14"
                namespace: ocp
          tests:
            - as: e2e-hypershift-continuous
              cron: 0 0 * * 0
              steps:
                cluster_profile: aws-cspi-qe
                env:
                  BASE_DOMAIN: cspilp.interop.ccitredhat.com
                  HYPERSHIFT_BASE_DOMAIN: cspilp.interop.ccitredhat.com
                  COMPUTE_NODE_REPLICAS: "4"
                test:
                  - as: operator-e2e
                    commands: make USER_MANAGEMENT_ALLOWED=false test-e2e-with-kafka
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                workflow: cucushift-installer-rehearse-aws-ipi-ovn-hypershift-guest
      - name: "osd" # Results in openshift-knative-serverless-operator-<BRANCH>__<OCP_VERSION>-osd.yaml
        releaseBuildConfiguration:
          base_images:
            cli-ocm:
              name: cli-ocm
              namespace: ci
              tag: latest
          tests:
            - as: e2e-osd-continuous
              cron: 0 0 * * 0
              steps:
                cluster_profile: osd-ephemeral
                env:
                  CLUSTER_DURATION: "10800"
                  CLUSTER_VERSION: "4.14"
                  COMPUTE_NODES: "4"
                post:
                  - chain: gather
                  - ref: osd-delete-delete
                pre:
                  - ref: ipi-install-rbac
                  - ref: osd-create-create
                test:
                  - as: operator-e2e
                    commands: make test-e2e-with-kafka
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
      - name: "single-node" # Results in openshift-knative-serverless-operator-<BRANCH>__<OCP_VERSION>-single-node.yaml
        releaseBuildConfiguration:
          tests:
            - as: e2e-sno-continuous
              cron: 0 0 * * 0
              steps:
                cluster_profile: gcp
                test:
                  - as: operator-e2e
                    commands: make HA=false test-e2e-with-kafka
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                workflow: openshift-e2e-gcp-single-node
              timeout: 8h0m0s
      - name: "vsphere" # Results in openshift-knative-serverless-operator-<BRANCH>__<OCP_VERSION>-vsphere.yaml
        releaseBuildConfiguration:
          base_images:
            upi-installer:
              name: "4.14"
              namespace: ocp
              tag: upi-installer
          tests:
            - as: e2e-vsphere-continuous
              cron: 0 0 * * 0
              steps:
                cluster_profile: vsphere-2
                test:
                  - as: operator-e2e
                    commands: make HA=false test-e2e-with-kafka
                    # dependencies: Generated by openshift-knative/hack
                    from: serverless-source-image
                    resources:
                      limits:
                        memory: 6Gi
                      requests:
                        cpu: 100m
                        memory: 200Mi
                workflow: openshift-e2e-vsphere-upi
