# Full struct in cmd/prowgen/prowgen.go#Config

config:
  branches:
    "source_image_cli_2":
      openShiftVersions:
        - 4.13
        #- 4.11

repositories:
  - org: mgencur
    repo: serverless-operator
    promotion:
      namespace: knative
    imagePrefix: serverless
    imageNameOverrides:
      serverless-operator: bundle
    slackChannel: "#serverless-ci"
    dockerfiles:
      matches:
        - "knative-operator/.*"
        - "openshift-knative-operator/.*"
        - "serving/metadata-webhook/.*"
        - "serving/ingress/.*"
        - "olm-catalog/serverless-operator/Dockerfile"
        - "olm-catalog/serverless-operator/index/Dockerfile"
    e2e:
      - regexp: "^operator-e2e$"
      - regexp: "^test-upgrade$"
      - regexp: "^upstream-e2e$"
        ignoreError: true
      - regexp: "^upstream-e2e-kafka$"
        ignoreError: true
      - regexp: "^mesh-e2e$"
        onDemand: true
        ignoreError: true
      - regexp: "^mesh-upgrade$"
        onDemand: true
        ignoreError: true
      - regexp: "^ui-e2e$"
        onDemand: true
        runIfChanged: "test/ui"
        ignoreError: true
      - regexp: "^kitchensink-e2e$"
        onDemand: true
        ignoreError: true
      - regexp: "^kitchensink-upgrade$"
        onDemand: true
        ignoreError: true
    resources:
      '*':
        limits:
          memory: 6Gi
        requests:
          cpu: 100m
          memory: 200Mi
