# Full struct in cmd/prowgen/prowgen.go#Config

config:
  branches:
    "release-v1.8":
      openShiftVersions:
        - version: 4.13
        - version: 4.10
    "release-v1.9":
      openShiftVersions:
        - version: 4.13
        - version: 4.10
    "release-v1.10":
      openShiftVersions:
        - version: 4.14
        - version: 4.11
    "release-v1.11":
      openShiftVersions:
        - version: 4.14
        - version: 4.11
    "release-v1.12":
      openShiftVersions:
        - version: 4.14
        - version: 4.11
    "release-next":
      openShiftVersions:
        - version: 4.14
        - version: 4.11

repositories:
  - org: openshift-knative
    repo: serving
    imagePrefix: knative-serving
    imageNameOverrides:
      migrate: storage-version-migration
    slackChannel: "#knative-serving-ci"
    e2e:
      - match: ".*e2e$"
      - match: ".*e2e-tls$"
      - match: "perf-tests$"
        onDemand: true
    resources:
      '*':
        requests:
          cpu: 500m
          memory: 4Gi
